# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "50"
  creationTimestamp: "2022-03-27T16:58:06Z"
  generation: 50
  labels:
    app: maverics
  name: maverics
  namespace: default
  resourceVersion: "16432131"
  uid: 82fc6093-07e1-4fe3-9112-11e4d92ece7f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: maverics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maverics
    spec:
      containers:
      - env:
        - name: MAVERICS_DEBUG_MODE
          value: "true"
        image: poddar009/maverics-debug:0.6.29.48
        imagePullPolicy: IfNotPresent
        name: maverics-debug
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-hub-cred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-04-27T03:18:42Z"
    lastUpdateTime: "2022-04-27T03:18:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-27T16:58:07Z"
    lastUpdateTime: "2022-04-27T03:37:47Z"
    message: ReplicaSet "maverics-598bc98986" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 50
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
